# Generated by Django 4.2.3 on 2024-07-02 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findoviodb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='license',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
