# Generated by Django 4.2.3 on 2024-07-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('findoviodb', '0002_remove_payment_license_delete_license_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('kind_of_license', models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('plan_type', models.IntegerField(choices=[(0, 'Monthly'), (1, 'Annual')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('kind_of_license', models.IntegerField(choices=[(0, 'Free'), (1, 'Pro'), (2, 'Premium')])),
                ('kind_of_payment', models.IntegerField(choices=[(0, 'Monthly'), (1, 'Annual')])),
                ('license', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='findoviodb.license')),
            ],
        ),
    ]
